---
title: "R-loop comparison"
author: "Aiola Stoja"
date: "2023-11-16"
output: html_document
---
<style type="text/css">
   .main-container {max-width: 100%;}
   .row {display: flex;}
   .column {flex: 50%;}
</style>

```{r setup packages, include=FALSE}

library(readxl)
library(tidyr)
library(dplyr)
library(VennDiagram)
library(devtools)
#install_github("wjawaid/enrichR")
library(enrichR)
library(ggpubr)
library(kableExtra)
library(eulerr)
library(purrr)
library(ggplot2)
library(viridis)
library(stringr)


```


```{r readin table, include = FALSE}

my_data <- as.list(read_xlsx("tables1_Helicases_in_R-loop_Formation_and_Resolution.xlsx")) 

my_data_names<- sapply(my_data,'[[',1)

names(my_data) <- c(my_data_names[[1]], my_data_names[[2]], my_data_names[[3]], my_data_names[[4]], my_data_names[[5]], my_data_names[[6]])


#%>%
 #map(function(a) a[-1]) 

#naomit_mydata <- lapply(my_data, function(x) x[!is.na(x)]) %>%
 # map(function(a) a[-1]) 


naomit_mydata_semicolonseperated <- my_data %>%
  map(function(v) v[-1]) %>% #remove the first row (it was either blank or not necessary)
  map(function(w) w[!is.na(w)]) %>% #remove all na values in the list
  map(function(x) strsplit(as.character(x), ";")) %>% #split any values in the list/data frame by semicolon, and send to a new row
  map(function(y) unlist(y)) %>% # add each column to a sepearate list
  map(function(z) unique(z)) #remove any duplicate values

```

<div class = "row">
<div class = "column">

## Venn Diagrams {.tabset}

### Comparing genes from two different RNaseH experiments

```{r venn diagram of rnaseH comparison , echo=FALSE,message=FALSE, warning=FALSE}

genes.venn_rnaseH <- euler(c(naomit_mydata_semicolonseperated[4], naomit_mydata_semicolonseperated[5]))
plot(genes.venn_rnaseH, quantities = list(type = c("counts", "percent"), cex = 1.6), labels = list(cex=0.5), adjust_labels = TRUE)

```

### Comparing genes from two different S9.6 experiments

```{r venn diagram  s9.6 comparison seperately, echo=FALSE,message=FALSE, warning=FALSE}

genes.venn_s9.6 <- euler(c(naomit_mydata_semicolonseperated[1], naomit_mydata_semicolonseperated[3]))
plot(genes.venn_s9.6, quantities = list(type = c("counts", "percent"), cex = 2), labels = list(cex=0.7), adjust_labels = TRUE)


```

### Comparing all RNaseH and S9.6 genes 

```{r venn diagram for all rnaseh combined and all s9.6 combined, echo=FALSE,message=FALSE, warning=FALSE}

rnaseh_combined <- mapply(c, naomit_mydata_semicolonseperated[4], naomit_mydata_semicolonseperated[5]) %>%
  unique() #if you want to see which are duplicated, you can do duplicated()
s9.6_combined <- mapply(c, naomit_mydata_semicolonseperated[1], naomit_mydata_semicolonseperated[3]) %>%
  unique()

combined_list <- list(rnaseh_combined, s9.6_combined)

names(combined_list) <- c("rnaseh_combined", "s9.6_combined")

genes.venn_combined <- euler(combined_list)
plot(genes.venn_combined, quantities = list(type = c("counts", "percent"), cex = 2), fills = c("blue", "purple", "green"), adjust_labels = TRUE)



combinedVennPartition <- get.venn.partitions(combined_list)
listCombinedV.P <- setNames(as.list(combinedVennPartition$..values..), combinedVennPartition$..set..)

```

</div>

<div class = "column">



```{r setup for Pathway analysis , include=FALSE}

websiteLive <- getOption("enrichR.live")
if (websiteLive) {
    listEnrichrSites()
    setEnrichrSite("Enrichr")
    dbs <- listEnrichrDbs()
    # Human genes   
}

dbs <- c("GO_Molecular_Function_2015", "GO_Cellular_Component_2015", "GO_Biological_Process_2015")

```


```{r Pathway analysis for combined rnaseh and s9.6 venn diagram, echo=FALSE, message=FALSE, warning=FALSE, results = 'hide'}

##Shared 

if (websiteLive) {
    enrichedCombinedShared <- enrichr(listCombinedV.P[["rnaseh_combined∩s9.6_combined"]], dbs)
    plotEnrich(enrichedCombinedShared$GO_Biological_Process_2015, showTerms = 20, numChar = 40, y = "Count", orderBy = "Adjusted.P.value", 
    title = "Rnaseh and s9.6 shared genes") + scale_fill_gradientn(colours = terrain.colors(20))
}

##RnaseH only


if (websiteLive) {
    enrichedCombinedRnaseH <- enrichr(listCombinedV.P[["(rnaseh_combined)∖(s9.6_combined)"]], dbs)
    plotEnrich(enrichedCombinedRnaseH$GO_Biological_Process_2015, showTerms = 20, numChar = 40, y = "Count", orderBy = "Adjusted.P.value", 
    title = "Rnaseh only genes")+ scale_fill_gradientn(colours = viridis(n=256, option = "C"))
}


##S9.6 only

if (websiteLive) {
    enrichedCombinedS9.6 <- enrichr(listCombinedV.P[["(s9.6_combined)∖(rnaseh_combined)"]], dbs)
    plotEnrich(enrichedCombinedS9.6$GO_Biological_Process_2015, showTerms = 20, numChar = 40, y = "Count", orderBy = "Adjusted.P.value", 
    title = "S9.6 only genes" ) + scale_fill_gradientn(colours = viridis(256, option = "D"))
}



```

```{r trying to get unique pathways, echo=FALSE, message=FALSE, warning=FALSE, results = 'hide'}

df1 <- as.data.frame(enrichedCombinedRnaseH$GO_Biological_Process_2015)
df2 <- as.data.frame(enrichedCombinedS9.6$GO_Biological_Process_2015)
df3 <- as.data.frame(enrichedCombinedShared$GO_Biological_Process_2015)

antijoin <- anti_join(df_GOCombinedRnaseH, df_GOCombinedShared, by = "Term")


list_GOcombined<- list(df_GOCombinedRnaseH, 
                       df_GOCombinedS9.6, 
                       df_GOCombinedShared)
names(list_GOcombined) <- c("RnaseH_combined_GObiologicalprocess", "S9.6_combined_GObiologicalprocess", "combined_shared_GObiologicalprocess")


list_GOcombined2 <- lapply(list_GOcombined, function(z) z[!duplicated(z$),])

df_varnames <- ls()[ grep("^df[0-9]+$", ls()) ]
dflist <- sapply(df_varnames, get, simplify = FALSE)
dflist2 <- lapply(dflist, function(z) z[!duplicated(z$id),])

dflist$df1$Term

dflist$df1$Term

list_GOcombined$RnaseH_combined_GObiologicalprocess$Term

list_GOcombined[[Term]]


list_GOcombined$RnaseH_combined_GObiologicalprocess$Term

df2_GOCombinedRnaseH <- as.data.frame(res$RnaseH_combined_GObiologicalprocess)
df2_GOCombinedS9.6 <- as.data.frame(res$S9.6_combined_GObiologicalprocess)
df2_GOCombinedShared <- as.data.frame(res$combined_shared_GObiologicalprocess)


un <- unlist(list_GOcombined)
res <- Map(`[`, list_GOcombined, relist(!duplicated(list_GOcombined), skeleton = list_GOcombined))

```

